export type HousingType =
  | 'Maison'
  | 'Appartement'
  | 'Grange'
  | 'Chambre d\'hôtes'
  | 'Bateau'
  | 'Cabane'
  | 'Caravane ou camping-car'
  | 'Casa particular'
  | 'Château'
  | 'Maison troglodyte'
  | 'Conteneur maritime'
  | 'Maison cycladique'
  | 'Dammuso'
  | 'Dôme'
  | 'Maison organique'
  | 'Ferme'
  | 'Maison d\'hôtes'
  | 'Hôtel'
  | 'Logement sur l\'eau'
  | 'Kezhan'
  | 'Minsu'
  | 'Riad'
  | 'Ryokan'
  | 'Cabane de berger'
  | 'Tente'
  | 'Tiny house'
  | 'Tour'
  | 'Cabane perchée'
  | 'Trullo'
  | 'Moulin à vent'
  | 'Yourte';
